# Generated by Django 5.1.6 on 2025-03-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='frstname',
            new_name='firstname',
        ),
    ]
