# Generated by Django 4.2.11 on 2025-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_rename_frstname_student_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
